# Generated by Django 3.1.5 on 2021-03-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='BlogApp.Categoria'),
        ),
    ]
